query getforum {
  forum (where: { status: { _gte: 1, _lte: 2 } }){
    topic
    comments_aggregate(order_by: {forum: {comments_aggregate: {count: desc}}}){
      aggregate {
        count
      }
    }
    forum_histories_aggregate(order_by: {forum: {forum_histories_aggregate: {count: desc}}} ) {
      aggregate {
        count
      }
    }
    ratings_aggregate(order_by: {score: desc} ) {
      aggregate {
        count
      }
    }
  }
}

